sonar.organization=kanokkarn13
sonar.projectKey=Kanokkarn13_HSK-Vocabulary-Frequency
sonar.sources=backend,etl,frontend/src
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=notebooks/**,data/**,tests/**
